version: '3.8'

services:
  web:
    build: ./web
    container_name: web
    ports:
      - "3001:80"
    restart: always

  client:
    build: ./client
    container_name: client
    ports:
      - "3002:80"
    restart: always

  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    restart: always