networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - server
      - client
      - web
    networks:
      - dev
    

  server:
    build:
      context: ./server
    networks:
      - dev

  client:
    build:
      context: ./client
    networks:
      - dev
  
  web:
    build:
      context: ./web
    networks:
      - dev