version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - client
      - server 

  web:
    build: ./web
    container_name: web
    restart: always
    volumes:
      - /usr/share/nginx/html/web

  client:
    build: ./client
    container_name: client
    restart: always
    volumes:
      - /usr/share/nginx/html/client

  server:
    build: ./server
    container_name: server
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=5000
    ports:
      - "5000:5000"
